# HWHash configuration parameters.
# In most cases, they do not need to be changed.
HighPrecision: true
HighPriority: true
Delay: 500

# Sensor values to be sent to serial output.
# String must be the current sensor name in HWiNFO.
Sensors:
#  - "CPU (Tctl/Tdie)"
#  - "GPU Hot Spot Temperature"

# Serialport settings.
PortName: "COM3"
BaudRate: 115200